version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: pagos-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: pagos-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"    # RabbitMQ Broker
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  pagos-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pagos-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/pagosdb
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      APP_RABBITMQ_EXCHANGE: pagos.estatus.cambiado
      APP_RABBITMQ_ROUTING-KEY: estatus.cambiado.general

volumes:
  mongo-data:

