spring:
  application:
    name: pagos-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/pagosdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

rabbitmq:
  exchange: pagos.estatus.cambiado
  routing-key: estatus.cambiado.general
  listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 5000
          multiplier: 2.0
