spring:
  application:
    name: pagos-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/pagosdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 5000ms
          max-attempts: 3
          multiplier: 2.0

server:
  port: 8080

app:
  rabbitmq:
    exchange: pagos.estatus.cambiado
    routing-key: estatus.cambiado.general
